### ISSUE TITLE
运行出现错误 看不懂 求赐教

### ISSUE THREAD

**Issue by vuens** [dingguotu/ddns#1]
```
$python /root/ddns/py-dnspod-ddns/ddns.py
Traceback (most recent call last):
  File "/root/ddns/py-dnspod-ddns/ddns.py", line 42, in <module>
    conf = json.load(open(os.path.join(os.path.dirname(os.path.realpath(__file__)), "conf.json"), "r"))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 15 (char 33)
```

**Comment by vuens** [comment]
还有就是配置文件修改的时候`<>`要不要留下？ py 0基础渣渣 求教

**Comment by dingguotu** [comment]
这个错误看上去是读取json文件出错，你是不是修改配置文件的时候格式不对，先把<>去掉换成“”，然后试试

**Comment by dingguotu** [comment]
格式类似于这样
![_20181011232135](https://user-images.githubusercontent.com/17001225/46814946-6a857400-cdac-11e8-95f2-ceb65f243568.png)

**Comment by vuens** [comment]
> 格式类似于这样
> ![_20181011232135](https://user-images.githubusercontent.com/17001225/46814946-6a857400-cdac-11e8-95f2-ceb65f243568.png) 可以了，看了下我的配置少了个 ] 闭合，非常感谢！
